# Generated by Django 5.0.7 on 2024-07-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_cart_product_des_remove_cart_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_qty',
            new_name='products_qty',
        ),
    ]
