# Generated by Django 5.0.7 on 2024-08-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
