# Generated by Django 5.0.7 on 2024-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipncode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
