# Generated by Django 5.0.7 on 2024-08-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_address_zipncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zipncode',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
