# Generated by Django 5.0.7 on 2024-08-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
