# Generated by Django 5.0.7 on 2024-08-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_delivery_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='products',
            field=models.CharField(max_length=1000),
        ),
    ]
